# Generated by Django 3.2 on 2021-04-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500, verbose_name='Category Name')),
                ('category_description', models.TextField(verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('product_size', models.CharField(max_length=50, verbose_name='Product Size')),
                ('product_price', models.IntegerField(verbose_name='Product Price')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
