# Generated by Django 3.2 on 2021-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='most_wanted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='newly_arrived',
            field=models.BooleanField(default=True),
        ),
    ]
