# Generated by Django 3.2 on 2021-04-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0004_auto_20210430_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('products', models.ManyToManyField(to='Storage.Product', verbose_name='Added Cart Products')),
            ],
        ),
    ]
